### ISSUE TITLE
Should pull the GAM HEAD?

### ISSUE THREAD

**Issue by evansharp** [goodeggs/homebrew-it#1]
This is really convenient and I thank you very much for writing the formula!

Shouldn't the install script pull the most recent GAM version though, rather than hardcoding 3.62?

Is this possible?

**Comment by bobzoller** [comment]
I _think_ the homebrew pattern is to hardcode the latest release version, and then you can also see we provide your repo to the `head` method.  This allows folks to do a `brew install gam` to get the latest blessed version, or `brew install --HEAD gam` to get it straight from Github.

But honestly I'm a homebrew recipe newbie, so I'm happy to get corrected.

Also: it'd be cool to get @jay0lee to take ownership and submit it to homebrew proper (see [these instructions](http://stackoverflow.com/a/33303246)) ... we just created this because we needed it internally, but I don't expect the general public to tap goodeggs/it ;)
